// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipv4.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ipv4_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ipv4_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ipv4_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ipv4_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ipv4_2eproto;
namespace Proto {
class IPv4;
struct IPv4DefaultTypeInternal;
extern IPv4DefaultTypeInternal _IPv4_default_instance_;
}  // namespace Proto
PROTOBUF_NAMESPACE_OPEN
template<> ::Proto::IPv4* Arena::CreateMaybeMessage<::Proto::IPv4>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Proto {

// ===================================================================

class IPv4 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto.IPv4) */ {
 public:
  inline IPv4() : IPv4(nullptr) {}
  ~IPv4() override;
  explicit PROTOBUF_CONSTEXPR IPv4(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IPv4(const IPv4& from);
  IPv4(IPv4&& from) noexcept
    : IPv4() {
    *this = ::std::move(from);
  }

  inline IPv4& operator=(const IPv4& from) {
    CopyFrom(from);
    return *this;
  }
  inline IPv4& operator=(IPv4&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IPv4& default_instance() {
    return *internal_default_instance();
  }
  static inline const IPv4* internal_default_instance() {
    return reinterpret_cast<const IPv4*>(
               &_IPv4_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(IPv4& a, IPv4& b) {
    a.Swap(&b);
  }
  inline void Swap(IPv4* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IPv4* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IPv4* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IPv4>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const IPv4& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const IPv4& from) {
    IPv4::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IPv4* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto.IPv4";
  }
  protected:
  explicit IPv4(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kListFieldNumber = 1,
  };
  // repeated string list = 1;
  int list_size() const;
  private:
  int _internal_list_size() const;
  public:
  void clear_list();
  const std::string& list(int index) const;
  std::string* mutable_list(int index);
  void set_list(int index, const std::string& value);
  void set_list(int index, std::string&& value);
  void set_list(int index, const char* value);
  void set_list(int index, const char* value, size_t size);
  std::string* add_list();
  void add_list(const std::string& value);
  void add_list(std::string&& value);
  void add_list(const char* value);
  void add_list(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& list() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_list();
  private:
  const std::string& _internal_list(int index) const;
  std::string* _internal_add_list();
  public:

  // @@protoc_insertion_point(class_scope:Proto.IPv4)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> list_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ipv4_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// IPv4

// repeated string list = 1;
inline int IPv4::_internal_list_size() const {
  return _impl_.list_.size();
}
inline int IPv4::list_size() const {
  return _internal_list_size();
}
inline void IPv4::clear_list() {
  _impl_.list_.Clear();
}
inline std::string* IPv4::add_list() {
  std::string* _s = _internal_add_list();
  // @@protoc_insertion_point(field_add_mutable:Proto.IPv4.list)
  return _s;
}
inline const std::string& IPv4::_internal_list(int index) const {
  return _impl_.list_.Get(index);
}
inline const std::string& IPv4::list(int index) const {
  // @@protoc_insertion_point(field_get:Proto.IPv4.list)
  return _internal_list(index);
}
inline std::string* IPv4::mutable_list(int index) {
  // @@protoc_insertion_point(field_mutable:Proto.IPv4.list)
  return _impl_.list_.Mutable(index);
}
inline void IPv4::set_list(int index, const std::string& value) {
  _impl_.list_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:Proto.IPv4.list)
}
inline void IPv4::set_list(int index, std::string&& value) {
  _impl_.list_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:Proto.IPv4.list)
}
inline void IPv4::set_list(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.list_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:Proto.IPv4.list)
}
inline void IPv4::set_list(int index, const char* value, size_t size) {
  _impl_.list_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Proto.IPv4.list)
}
inline std::string* IPv4::_internal_add_list() {
  return _impl_.list_.Add();
}
inline void IPv4::add_list(const std::string& value) {
  _impl_.list_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:Proto.IPv4.list)
}
inline void IPv4::add_list(std::string&& value) {
  _impl_.list_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:Proto.IPv4.list)
}
inline void IPv4::add_list(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.list_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:Proto.IPv4.list)
}
inline void IPv4::add_list(const char* value, size_t size) {
  _impl_.list_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:Proto.IPv4.list)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
IPv4::list() const {
  // @@protoc_insertion_point(field_list:Proto.IPv4.list)
  return _impl_.list_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
IPv4::mutable_list() {
  // @@protoc_insertion_point(field_mutable_list:Proto.IPv4.list)
  return &_impl_.list_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Proto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ipv4_2eproto
