// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipv4.proto

#include "ipv4.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Proto {
PROTOBUF_CONSTEXPR IPv4::IPv4(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.list_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct IPv4DefaultTypeInternal {
  PROTOBUF_CONSTEXPR IPv4DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~IPv4DefaultTypeInternal() {}
  union {
    IPv4 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IPv4DefaultTypeInternal _IPv4_default_instance_;
}  // namespace Proto
static ::_pb::Metadata file_level_metadata_ipv4_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_ipv4_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ipv4_2eproto = nullptr;

const uint32_t TableStruct_ipv4_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Proto::IPv4, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Proto::IPv4, _impl_.list_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Proto::IPv4)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Proto::_IPv4_default_instance_._instance,
};

const char descriptor_table_protodef_ipv4_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nipv4.proto\022\005Proto\"\024\n\004IPv4\022\014\n\004list\030\001 \003("
  "\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_ipv4_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ipv4_2eproto = {
    false, false, 49, descriptor_table_protodef_ipv4_2eproto,
    "ipv4.proto",
    &descriptor_table_ipv4_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_ipv4_2eproto::offsets,
    file_level_metadata_ipv4_2eproto, file_level_enum_descriptors_ipv4_2eproto,
    file_level_service_descriptors_ipv4_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ipv4_2eproto_getter() {
  return &descriptor_table_ipv4_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ipv4_2eproto(&descriptor_table_ipv4_2eproto);
namespace Proto {

// ===================================================================

class IPv4::_Internal {
 public:
};

IPv4::IPv4(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Proto.IPv4)
}
IPv4::IPv4(const IPv4& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  IPv4* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.list_){from._impl_.list_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Proto.IPv4)
}

inline void IPv4::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.list_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

IPv4::~IPv4() {
  // @@protoc_insertion_point(destructor:Proto.IPv4)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void IPv4::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.list_.~RepeatedPtrField();
}

void IPv4::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void IPv4::Clear() {
// @@protoc_insertion_point(message_clear_start:Proto.IPv4)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.list_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* IPv4::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string list = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_list();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "Proto.IPv4.list"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* IPv4::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Proto.IPv4)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string list = 1;
  for (int i = 0, n = this->_internal_list_size(); i < n; i++) {
    const auto& s = this->_internal_list(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Proto.IPv4.list");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Proto.IPv4)
  return target;
}

size_t IPv4::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Proto.IPv4)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string list = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.list_.size());
  for (int i = 0, n = _impl_.list_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.list_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData IPv4::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    IPv4::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*IPv4::GetClassData() const { return &_class_data_; }


void IPv4::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<IPv4*>(&to_msg);
  auto& from = static_cast<const IPv4&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Proto.IPv4)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.list_.MergeFrom(from._impl_.list_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void IPv4::CopyFrom(const IPv4& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Proto.IPv4)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IPv4::IsInitialized() const {
  return true;
}

void IPv4::InternalSwap(IPv4* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.list_.InternalSwap(&other->_impl_.list_);
}

::PROTOBUF_NAMESPACE_ID::Metadata IPv4::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ipv4_2eproto_getter, &descriptor_table_ipv4_2eproto_once,
      file_level_metadata_ipv4_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Proto
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Proto::IPv4*
Arena::CreateMaybeMessage< ::Proto::IPv4 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Proto::IPv4 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
